version: '3.3'

services:
  email_blaster:
    # Passes thru ENV Values on the host
    environment:
      - DEBUG
      - TOKEN
    build:
      context: .
      dockerfile: Dockerfile
    restart: "no"
    command: "true"
    volumes:
      - MailBlasterData:/config:rw
volumes:
  MailBlasterData:
