version: '3.3'

services:
  email_blaster:
    # Passes thru ENV Values on the host
    environment:
      - DEBUG
      - TOKEN
      - EMAIL
      - EMAILPASSWORD
      - EMAILSERVER
      - ALERTSROLE
      - ALERTSCHANNEL
    build:
      context: .
      dockerfile: Dockerfile
    restart: "no"
    command: "true"
    volumes:
      - MailBlasterData:/app/config:rw
volumes:
  MailBlasterData:
