version: '3.3'

services:
  email_blaster:
    build:
      context: .
      dockerfile: Dockerfile
    restart: "no"
    command: "true"
    volumes:
      # Mount ~/MailBlaster-config on the host to /config inside the container
      - ~/MailBlaster-config:/config:rw
