version: '3.3'

services:
  email_blaster:
    # Passes thru ENV Values on the host
    environment:
      - DEBUG
      - TOKEN
    image: ghcr.io/frc-1721/mailblaster:release
    restart: "no"
    command: "true"
    volumes:
      - MailBlasterData:/config:rw
volumes:
  MailBlasterData:
